# Site settings
title: The Thug Myth Project
email: hello@thethugmythproject.com
description: > # this means to ignore newlines until "baseurl:"
  The Thug Myth Project is a platform created to tell the narrative of the word thug, as it relates to the African Diaspora.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thethugmythproject.com" # the base hostname & protocol for your site
twitter_username: thethugmythproject

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-60066014-1

# Build settings
markdown: rdiscount

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
